### PR TITLE
Instagram: include query parameters in thumbnail URL 

### LINKED ISSUE #30: Instagram retrieval failing
Reported by @tolima in shaarli/Shaarli#1711

> Hello,
> I'm not sure I post in the correct place. Sorry.
> The Webthumbnailer won't work with instagram. I tried with this kind of url :
> instagram.com/p/CLWSjk1nmB4
> or event the source image :
> scontent-cdg2-1.cdninstagram.com/v/t51.2885-15/e35/149498980_265678338333091_8839537338863229106_n.jpg?_nc_ht=scontent-cdg2-1.cdninstagram.com&_nc_cat=107&_nc_ohc=yubf5kMWtd0AX-X9Rvk&tp=1&oh=d8fdb3c09993056251b28105363bad0e&oe=6057AD6E
> But in both case there is no thumbnail.
> Is it normal ? Is there a workaround ?
> Thank you

### PR DESCRIPTION
**Pull request by ArthurHoaro**
Retrieval now fails without them with an error stating: 'Bad URL timestamp'

Fixes #30

### CODE REVIEW

**Comment by tolima** [comment]
Don't work for me. 
What I do to have a thumbnails with Instagram :
- In rules.json I delete the Instagram part.
- on Instagram I go to the page where the image is.
- I find the url source of the image in the code source 
- I share this url source in shaarli and it works

**Comment by ArthurHoaro** [comment]
How did you test this change?

**Comment by tolima** [comment]
On Shaarli, after replace web-thumbnailer by the last one.
I try on :
- an instagram profil page (ex: https://www.instagram.com/melfindash/ )
- an instagram image page (ex: https://www.instagram.com/p/CLobRofBfN2/ )
- the source images (ex: https://scontent-cdg2-1.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/152045113_434431194280720_5656323718043532716_n.jpg?_nc_ht=scontent-cdg2-1.cdninstagram.com&_nc_cat=104&_nc_ohc=KWZooajXWOwAX8xYKFk&tp=1&oh=b5d71d699502e4cdd8d3efee45f5f951&oe=605F7A5B )

It won't make a thumbnail. But doing what I explain in the previous message work.
May be it's not the better way to test.

**Comment by ArthurHoaro** [comment]
Sorry for the late reply. I just tried and it's working for me with the picture page. Note that I had to clear my thumbnails cache. However the profile one doesn't because Instagram redirects to the login page.

Let me update the dependency in Shaarli and try with a the real release.

**Comment by ArthurHoaro** [comment]
It actually doesn't work on my production environment because Instagram redirects me to the login page even for picture pages. I need to investigate further to see if it's related to my IP, or if there are some headers that could be injected to avoid that.

**Comment by iooner** [comment]
Hi!
Maybe try ? 

https://www.instagram.com/p/ --- ID --- /media/?size=l
https://www.instagram.com/p/CLobRofBfN2/media/?size=l

**Pull request merged**
